name = "blockzone-universal-backend"
main = "shared/workers/universal-backend.js"
compatibility_date = "2024-01-01"

# Environment for production
[env.production]
name = "blockzone-universal-backend"
kv_namespaces = [
  { binding = "PLAYERS", id = "your-kv-namespace-id" },
  { binding = "SCORES", id = "your-scores-kv-id" },
  { binding = "ANALYTICS", id = "your-analytics-kv-id" }
]

# Environment for development
[env.staging]
name = "blockzone-universal-backend-staging"
kv_namespaces = [
  { binding = "PLAYERS", id = "your-dev-kv-namespace-id" },
  { binding = "SCORES", id = "your-dev-scores-kv-id" },
  { binding = "ANALYTICS", id = "your-dev-analytics-kv-id" }
]

# Variables for API endpoints
[vars]
ENVIRONMENT = "development"
API_VERSION = "1.0"
